name: Static tests

on:
    pull_request:
        branches:
        - main

jobs:
    static_tests:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Install dependencies
          run: npm ci --ignore-scripts

        - name: TypeScript
          run: npm run ts-check

        - name: Lint
          run: npm run lint:nofix